# Generated by Django 3.0.6 on 2020-10-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type_sv',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='item_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='expense.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='expense.Category'),
        ),
    ]
