# Generated by Django 3.0.6 on 2020-10-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20201003_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(blank=True)),
            ],
        ),
    ]
