# Generated by Django 3.0.6 on 2020-10-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='expense.PaymentMethod'),
        ),
    ]
