# Generated by Django 3.0.6 on 2020-10-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='account_id',
            new_name='account_sv',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='place_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
