# Generated by Django 3.0.6 on 2020-10-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_auto_20201004_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='method_id',
        ),
    ]
